### ISSUE TITLE
Won't compile...

### ISSUE THREAD

**Issue by caecos** [mrVanDalo/VCVRecorder#1]
The sources cannot be compiled under MSYS2

**Comment by mrVanDalo** [comment]
What about the [dekstop Recorder](https://github.com/dekstop/vcvrackplugins_dekstop) ? Does it compile under your MSYS2 ?

And what vcvrack version do you use ? I only tested it under 0.5.1

**Comment by caecos** [comment]
No cannot compile either...

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mrVanDalo** [comment]
Ok Sorry than. I hacked this thing quickly by modding the dekstop Recording. I currently have no time to "release" it properly.

**Comment by caecos** [comment]
It’s OK no stress ;D

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SteveRussell33** [comment]
Will you be updating this for VCV 0.6.2?

**Comment by mrVanDalo** [comment]
Uh I don't think so. ... have to do to much stuff. (no time for it :( ) but a PR or a fork would be welcome.

**Comment by mrVanDalo** [comment]
Sorry I don't have time to look at this project anymore. I'll close the issue, feel free to clone my repo and fix it yourself.
